FROM node:16-alpine as build
WORKDIR /dumbmerch-fe
COPY . /dumbmerch-fe
RUN npm install
RUN npm run build


FROM node:16-alpine
COPY --from=build /dumbmerch-fe /dumbmerch-fe
WORKDIR /dumbmerch-fe
RUN npm install -g serve
EXPOSE 3000
CMD ["serve","-s","build"]

